print("##################################PythonExplorer##########################")
print("#                                                                        #")
print("#                          Welcome to PythonExplorer                     #")
print("#                                                                        #")
print("#                          This GUI is in beta                           #")
print("#                                                                        #")
print("#                   Are you sure you want to continue?                   #")
print("#                                                                        #")
print("#                         [ Yes  ]              [ No ]                   #")
print("#                                                                        #")
print("#           Help?  Type the Text in the button to press it               #")
print("#                                                                        #")
print("##########################################################################")
